### ISSUE TITLE
From Youtube :)

### ISSUE THREAD

**Issue by ryanheath** [zoran-horvat/advent-of-code-2024#2]
[Day1.txt](https://github.com/user-attachments/files/18044408/Day1.txt)

The accepted score is 27647262

**Comment by zoran-horvat** [comment]
Thank you Ryan, you were right from the beginning!

My version did not account with the last point in the specification, which tells what to do when a number appears multiple times on the left.

The improved Day 1 solution in this repo is fixing the issue, and now it prints the same value you have came with.

Thank you for pointing out this problem!
